import type { CctvCamera } from './types';

// OpenCV/FFmpeg MJPEG stream server — same approach as bloodcat_map.py
// Deploy: github.com/blackglobeco/bl4ckgl0be-stream → Render (Singapore)
const STREAM_HOST = process.env.NEXT_PUBLIC_STREAM_HOST ?? '';

export function getBlackeyeCameras(): CctvCamera[] {
  if (!STREAM_HOST) return [];
  return [
    {
      id: 'blackeye-1.54.234.23',
      lat: 21.0184,
      lng: 105.8461,
      name: 'Blackeye – Hanoi',
      city: 'Hanoi',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMS41NC4yMzQuMjM6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-1.9.246.147',
      lat: 3.0617,
      lng: 101.4621,
      name: 'Blackeye – Klang',
      city: 'Klang',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMS45LjI0Ni4xNDc6NTU0L2NhbS9yZWFsbW9uaXRvcj9jaGFubmVsPTEmc3VidHlwZT0w`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-100.11.83.185',
      lat: 40.2363,
      lng: -75.296,
      name: 'Blackeye – Lansdale',
      city: 'Lansdale',
      country: 'United States',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTAwLjExLjgzLjE4NTo1NTQvMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-100.15.31.156',
      lat: 38.6273,
      lng: -76.9859,
      name: 'Blackeye – Waldorf',
      city: 'Waldorf',
      country: 'United States',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTAwLjE1LjMxLjE1Njo1NTQvU3RyZWFtaW5nL0NoYW5uZWxzLzEwMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-100.4.105.174',
      lat: 37.11,
      lng: -76.5115,
      name: 'Blackeye – Newport News',
      city: 'Newport News',
      country: 'United States',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTAwLjQuMTA1LjE3NDo1NTQvY2gxXzAuaDI2NA==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-101.109.233.72',
      lat: 13.7101,
      lng: 100.4543,
      name: 'Blackeye – Bangkok',
      city: 'Bangkok',
      country: 'Thailand',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTAxLjEwOS4yMzMuNzI6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-101.109.35.142',
      lat: 14.0517,
      lng: 101.3653,
      name: 'Blackeye – Prachin Buri',
      city: 'Prachin Buri',
      country: 'Thailand',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTAxLjEwOS4zNS4xNDI6NTU0LzEx`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-101.78.66.94',
      lat: 1.3756,
      lng: 103.7685,
      name: 'Blackeye – Singapore',
      city: 'Singapore',
      country: 'Singapore',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTAxLjc4LjY2Ljk0OjU1NC9TdHJlYW1pbmcvQ2hhbm5lbHMvMTAx`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-103.234.254.133',
      lat: -6.2208,
      lng: 106.8403,
      name: 'Blackeye – Jakarta',
      city: 'Jakarta',
      country: 'Indonesia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTAzLjIzNC4yNTQuMTMzOjU1NC9jYW0vcmVhbG1vbml0b3I/Y2hhbm5lbD0xJnN1YnR5cGU9MCZ1bmljYXN0PXRydWUmcHJvdG89b252aWY=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-103.4.46.246',
      lat: 3.0497,
      lng: 101.56,
      name: 'Blackeye – Shah Alam',
      city: 'Shah Alam',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTAzLjQuNDYuMjQ2OjU1NC9jYW0vcmVhbG1vbml0b3I/Y2hhbm5lbD0xJnN1YnR5cGU9MA==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-103.6.48.74',
      lat: 22.2578,
      lng: 114.1657,
      name: 'Blackeye – Hong Kong',
      city: 'Hong Kong',
      country: 'Hong Kong',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTAzLjYuNDguNzQ6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-104.151.131.242',
      lat: 46.0693,
      lng: -72.8231,
      name: 'Blackeye – Pierreville',
      city: 'Pierreville',
      country: 'Canada',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTA0LjE1MS4xMzEuMjQyOjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-104.231.240.179',
      lat: 43.0804,
      lng: -88.0224,
      name: 'Blackeye – Wauwatosa',
      city: 'Wauwatosa',
      country: 'United States',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTA0LjIzMS4yNDAuMTc5OjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-104.240.4.211',
      lat: 38.0834,
      lng: -81.8303,
      name: 'Blackeye – Danville',
      city: 'Danville',
      country: 'United States',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTA0LjI0MC40LjIxMTo1NTQvY2gxXzAuaDI2NA==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-104.34.245.104',
      lat: 33.8225,
      lng: -118.3103,
      name: 'Blackeye – Torrance',
      city: 'Torrance',
      country: 'United States',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTA0LjM0LjI0NS4xMDQ6NTU0L2NhbS9yZWFsbW9uaXRvcj9jaGFubmVsPTEmc3VidHlwZT0w`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-104.4.45.113',
      lat: 39.7436,
      lng: -86.1158,
      name: 'Blackeye – Indianapolis',
      city: 'Indianapolis',
      country: 'United States',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTA0LjQuNDUuMTEzOjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-107.11.217.220',
      lat: 41.3878,
      lng: -84.1416,
      name: 'Blackeye – Napoleon',
      city: 'Napoleon',
      country: 'United States',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTA3LjExLjIxNy4yMjA6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-107.207.236.51',
      lat: 36.0322,
      lng: -79.8588,
      name: 'Blackeye – Greensboro',
      city: 'Greensboro',
      country: 'United States',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTA3LjIwNy4yMzYuNTE6NTU0L2F4aXMtbWVkaWEvbWVkaWEuYW1w`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-108.172.65.242',
      lat: 49.2825,
      lng: -123.1291,
      name: 'Blackeye – Vancouver',
      city: 'Vancouver',
      country: 'Canada',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTA4LjE3Mi42NS4yNDI6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-108.21.71.210',
      lat: 40.7915,
      lng: -73.6924,
      name: 'Blackeye – Manhasset',
      city: 'Manhasset',
      country: 'United States',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTA4LjIxLjcxLjIxMDo1NTQvY2FtL3JlYWxtb25pdG9yP2NoYW5uZWw9MSZzdWJ0eXBlPTA=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-108.50.228.212',
      lat: 40.8137,
      lng: -74.1234,
      name: 'Blackeye – Lyndhurst',
      city: 'Lyndhurst',
      country: 'United States',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTA4LjUwLjIyOC4yMTI6NTU0L2NhbS9yZWFsbW9uaXRvcj9jaGFubmVsPTEmc3VidHlwZT0w`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-109.153.131.189',
      lat: 55.9707,
      lng: -4.0636,
      name: 'Blackeye – Glasgow',
      city: 'Glasgow',
      country: 'United Kingdom',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTA5LjE1My4xMzEuMTg5OjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-109.186.65.153',
      lat: 32.0729,
      lng: 34.8481,
      name: 'Blackeye – Giv‘at Shmuel',
      city: 'Giv‘at Shmuel',
      country: 'Israel',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTA5LjE4Ni42NS4xNTM6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-109.67.130.163',
      lat: 32.0804,
      lng: 34.7807,
      name: 'Blackeye – Tel Aviv',
      city: 'Tel Aviv',
      country: 'Israel',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTA5LjY3LjEzMC4xNjM6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-109.67.170.245',
      lat: 32.0804,
      lng: 34.7807,
      name: 'Blackeye – Tel Aviv',
      city: 'Tel Aviv',
      country: 'Israel',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTA5LjY3LjE3MC4yNDU6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-109.67.182.201',
      lat: 32.0804,
      lng: 34.7807,
      name: 'Blackeye – Tel Aviv',
      city: 'Tel Aviv',
      country: 'Israel',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTA5LjY3LjE4Mi4yMDE6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-110.136.98.16',
      lat: -6.2114,
      lng: 106.8446,
      name: 'Blackeye – Jakarta',
      city: 'Jakarta',
      country: 'Indonesia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTEwLjEzNi45OC4xNjo1NTQvbGl2ZS92aWRlby9wcm9maWxlMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-110.174.3.44',
      lat: -33.8653,
      lng: 151.1021,
      name: 'Blackeye – Sydney',
      city: 'Sydney',
      country: 'Australia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTEwLjE3NC4zLjQ0OjU1NC9jYW0vcmVhbG1vbml0b3I/Y2hhbm5lbD0xJnN1YnR5cGU9MQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-110.175.241.17',
      lat: -31.8544,
      lng: 115.8433,
      name: 'Blackeye – Perth',
      city: 'Perth',
      country: 'Australia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTEwLjE3NS4yNDEuMTc6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-110.4.4.163',
      lat: 22.2795,
      lng: 114.146,
      name: 'Blackeye – Central',
      city: 'Central',
      country: 'Hong Kong',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTEwLjQuNC4xNjM6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-112.141.122.149',
      lat: -34.8581,
      lng: 138.6127,
      name: 'Blackeye – Adelaide',
      city: 'Adelaide',
      country: 'Australia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTEyLjE0MS4xMjIuMTQ5OjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-112.141.171.32',
      lat: -37.8207,
      lng: 145.0408,
      name: 'Blackeye – Melbourne',
      city: 'Melbourne',
      country: 'Australia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTEyLjE0MS4xNzEuMzI6NTU0L2NhbS9yZWFsbW9uaXRvcj9jaGFubmVsPTEmc3VidHlwZT0w`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-112.197.61.82',
      lat: 10.822,
      lng: 106.6257,
      name: 'Blackeye – Ho Chi Minh City',
      city: 'Ho Chi Minh City',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTEyLjE5Ny42MS44Mjo1NTQvMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-113.162.132.234',
      lat: 10.822,
      lng: 106.6257,
      name: 'Blackeye – Ho Chi Minh City',
      city: 'Ho Chi Minh City',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTEzLjE2Mi4xMzIuMjM0OjU1NC9TdHJlYW1pbmcvQ2hhbm5lbHMvMTAx`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-113.163.157.170',
      lat: 16.1667,
      lng: 107.8333,
      name: 'Blackeye – Vietnam',
      city: 'Vietnam',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTEzLjE2My4xNTcuMTcwOjU1NC9TdHJlYW1pbmcvQ2hhbm5lbHMvMTAx`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-113.163.164.143',
      lat: 16.1667,
      lng: 107.8333,
      name: 'Blackeye – Vietnam',
      city: 'Vietnam',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTEzLjE2My4xNjQuMTQzOjU1NC9saXZlL3ZpZGVvL3Byb2ZpbGUx`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-113.164.66.198',
      lat: 21.0184,
      lng: 105.8461,
      name: 'Blackeye – Hanoi',
      city: 'Hanoi',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTEzLjE2NC42Ni4xOTg6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-113.169.83.238',
      lat: 10.8126,
      lng: 106.678,
      name: 'Blackeye – Go Vap',
      city: 'Go Vap',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTEzLjE2OS44My4yMzg6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-113.170.58.55',
      lat: 10.0361,
      lng: 105.7941,
      name: 'Blackeye – Can Tho',
      city: 'Can Tho',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTEzLjE3MC41OC41NTo1NTQvMA==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-113.176.70.49',
      lat: 21.0184,
      lng: 105.8461,
      name: 'Blackeye – Hanoi',
      city: 'Hanoi',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTEzLjE3Ni43MC40OTo1NTQvU3RyZWFtaW5nL0NoYW5uZWxzLzEwMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-113.179.45.132',
      lat: 20.9423,
      lng: 107.0727,
      name: 'Blackeye – Ha Long',
      city: 'Ha Long',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTEzLjE3OS40NS4xMzI6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-113.188.163.226',
      lat: 16.1667,
      lng: 107.8333,
      name: 'Blackeye – Vietnam',
      city: 'Vietnam',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTEzLjE4OC4xNjMuMjI2OjU1NC9TdHJlYW1pbmcvQ2hhbm5lbHMvMTAx`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-113.210.70.106',
      lat: 3.1071,
      lng: 101.6139,
      name: 'Blackeye – Petaling Jaya',
      city: 'Petaling Jaya',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTEzLjIxMC43MC4xMDY6NTU0L2NhbS9yZWFsbW9uaXRvcj9jaGFubmVsPTEmc3VidHlwZT0w`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-113.22.124.236',
      lat: 10.822,
      lng: 106.6257,
      name: 'Blackeye – Ho Chi Minh City',
      city: 'Ho Chi Minh City',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTEzLjIyLjEyNC4yMzY6NTU0L2NhbS9yZWFsbW9uaXRvcj9jaGFubmVsPTEmc3VidHlwZT0w`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-113.23.139.47',
      lat: 2.5,
      lng: 112.5,
      name: 'Blackeye – Malaysia',
      city: 'Malaysia',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTEzLjIzLjEzOS40Nzo1NTQvY2FtL3JlYWxtb25pdG9yP2NoYW5uZWw9MSZzdWJ0eXBlPTA=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-113.252.49.85',
      lat: 22.3346,
      lng: 114.2536,
      name: 'Blackeye – Tseung Kwan O',
      city: 'Tseung Kwan O',
      country: 'Hong Kong',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTEzLjI1Mi40OS44NTo1NTQvMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-113.253.169.191',
      lat: 22.3847,
      lng: 114.1965,
      name: 'Blackeye – Sha Tin Wai',
      city: 'Sha Tin Wai',
      country: 'Hong Kong',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTEzLjI1My4xNjkuMTkxOjU1NC9TdHJlYW1pbmcvQ2hhbm5lbHMvMTAx`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-115.130.188.58',
      lat: -27.5126,
      lng: 153.029,
      name: 'Blackeye – Brisbane',
      city: 'Brisbane',
      country: 'Australia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE1LjEzMC4xODguNTg6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-115.134.130.130',
      lat: 3.1408,
      lng: 101.6852,
      name: 'Blackeye – Kuala Lumpur',
      city: 'Kuala Lumpur',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE1LjEzNC4xMzAuMTMwOjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-115.134.130.134',
      lat: 3.1408,
      lng: 101.6852,
      name: 'Blackeye – Kuala Lumpur',
      city: 'Kuala Lumpur',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE1LjEzNC4xMzAuMTM0OjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-115.66.12.191',
      lat: 1.2872,
      lng: 103.8507,
      name: 'Blackeye – Singapore',
      city: 'Singapore',
      country: 'Singapore',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE1LjY2LjEyLjE5MTo1NTQvMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-115.66.78.206',
      lat: 1.3563,
      lng: 103.7542,
      name: 'Blackeye – Singapore',
      city: 'Singapore',
      country: 'Singapore',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE1LjY2Ljc4LjIwNjo1NTQvMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-115.70.28.128',
      lat: -31.9474,
      lng: 115.8648,
      name: 'Blackeye – Perth',
      city: 'Perth',
      country: 'Australia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE1LjcwLjI4LjEyODo1NTQvY2FtL3JlYWxtb25pdG9yP2NoYW5uZWw9MSZzdWJ0eXBlPTA=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-115.73.68.189',
      lat: 10.822,
      lng: 106.6257,
      name: 'Blackeye – Ho Chi Minh City',
      city: 'Ho Chi Minh City',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE1LjczLjY4LjE4OTo1NTQvbGl2ZS92aWRlby9wcm9maWxlMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-115.74.160.237',
      lat: 11.3085,
      lng: 106.0948,
      name: 'Blackeye – Tây Ninh',
      city: 'Tây Ninh',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE1Ljc0LjE2MC4yMzc6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-115.74.224.136',
      lat: 10.822,
      lng: 106.6257,
      name: 'Blackeye – Ho Chi Minh City',
      city: 'Ho Chi Minh City',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE1Ljc0LjIyNC4xMzY6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-115.74.245.65',
      lat: 10.822,
      lng: 106.6257,
      name: 'Blackeye – Ho Chi Minh City',
      city: 'Ho Chi Minh City',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE1Ljc0LjI0NS42NTo1NTQvU3RyZWFtaW5nL0NoYW5uZWxzLzEwMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-115.75.10.221',
      lat: 10.822,
      lng: 106.6257,
      name: 'Blackeye – Ho Chi Minh City',
      city: 'Ho Chi Minh City',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE1Ljc1LjEwLjIyMTo1NTQvU3RyZWFtaW5nL0NoYW5uZWxzLzEwMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-115.75.10.243',
      lat: 10.822,
      lng: 106.6257,
      name: 'Blackeye – Ho Chi Minh City',
      city: 'Ho Chi Minh City',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE1Ljc1LjEwLjI0Mzo1NTQvU3RyZWFtaW5nL0NoYW5uZWxzLzEwMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-115.75.24.116',
      lat: 10.822,
      lng: 106.6257,
      name: 'Blackeye – Ho Chi Minh City',
      city: 'Ho Chi Minh City',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE1Ljc1LjI0LjExNjo1NTQvY2FtMS9oMjY0`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-115.75.4.122',
      lat: 10.822,
      lng: 106.6257,
      name: 'Blackeye – Ho Chi Minh City',
      city: 'Ho Chi Minh City',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE1Ljc1LjQuMTIyOjU1NC9TdHJlYW1pbmcvQ2hhbm5lbHMvMTAx`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-115.78.236.37',
      lat: 10.822,
      lng: 106.6257,
      name: 'Blackeye – Ho Chi Minh City',
      city: 'Ho Chi Minh City',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE1Ljc4LjIzNi4zNzo1NTQvU3RyZWFtaW5nL0NoYW5uZWxzLzEwMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-115.79.199.156',
      lat: 10.822,
      lng: 106.6257,
      name: 'Blackeye – Ho Chi Minh City',
      city: 'Ho Chi Minh City',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE1Ljc5LjE5OS4xNTY6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-116.104.187.244',
      lat: 21.0184,
      lng: 105.8461,
      name: 'Blackeye – Hanoi',
      city: 'Hanoi',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE2LjEwNC4xODcuMjQ0OjU1NC9TdHJlYW1pbmcvQ2hhbm5lbHMvMTAx`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-116.108.76.174',
      lat: 10.0361,
      lng: 105.7941,
      name: 'Blackeye – Can Tho',
      city: 'Can Tho',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE2LjEwOC43Ni4xNzQ6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-116.109.136.26',
      lat: 16.1667,
      lng: 107.8333,
      name: 'Blackeye – Vietnam',
      city: 'Vietnam',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE2LjEwOS4xMzYuMjY6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-116.110.58.8',
      lat: 16.0685,
      lng: 108.2215,
      name: 'Blackeye – Da Nang',
      city: 'Da Nang',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE2LjExMC41OC44OjU1NC9TdHJlYW1pbmcvQ2hhbm5lbHMvMTAx`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-116.110.87.211',
      lat: 16.0685,
      lng: 108.2215,
      name: 'Blackeye – Da Nang',
      city: 'Da Nang',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE2LjExMC44Ny4yMTE6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-116.14.161.59',
      lat: 1.3248,
      lng: 103.8566,
      name: 'Blackeye – Singapore',
      city: 'Singapore',
      country: 'Singapore',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE2LjE0LjE2MS41OTo1NTQvMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-116.15.172.209',
      lat: 1.3652,
      lng: 103.8367,
      name: 'Blackeye – Singapore',
      city: 'Singapore',
      country: 'Singapore',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE2LjE1LjE3Mi4yMDk6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-116.15.180.177',
      lat: 1.3756,
      lng: 103.7685,
      name: 'Blackeye – Singapore',
      city: 'Singapore',
      country: 'Singapore',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE2LjE1LjE4MC4xNzc6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-116.15.63.32',
      lat: 1.385,
      lng: 103.7473,
      name: 'Blackeye – Singapore',
      city: 'Singapore',
      country: 'Singapore',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE2LjE1LjYzLjMyOjU1NC9TdHJlYW1pbmcvQ2hhbm5lbHMvMTAx`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-116.49.136.193',
      lat: 22.2578,
      lng: 114.1657,
      name: 'Blackeye – Hong Kong',
      city: 'Hong Kong',
      country: 'Hong Kong',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE2LjQ5LjEzNi4xOTM6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-116.86.125.213',
      lat: 1.3352,
      lng: 103.8529,
      name: 'Blackeye – Singapore',
      city: 'Singapore',
      country: 'Singapore',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE2Ljg2LjEyNS4yMTM6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-116.86.177.175',
      lat: 1.3352,
      lng: 103.8529,
      name: 'Blackeye – Singapore',
      city: 'Singapore',
      country: 'Singapore',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE2Ljg2LjE3Ny4xNzU6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-116.86.7.225',
      lat: 1.3343,
      lng: 103.8724,
      name: 'Blackeye – Singapore',
      city: 'Singapore',
      country: 'Singapore',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE2Ljg2LjcuMjI1OjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-116.89.6.142',
      lat: 1.385,
      lng: 103.7473,
      name: 'Blackeye – Singapore',
      city: 'Singapore',
      country: 'Singapore',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE2Ljg5LjYuMTQyOjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-116.98.130.232',
      lat: 16.1667,
      lng: 107.8333,
      name: 'Blackeye – Vietnam',
      city: 'Vietnam',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE2Ljk4LjEzMC4yMzI6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-116.98.227.48',
      lat: 16.1667,
      lng: 107.8333,
      name: 'Blackeye – Vietnam',
      city: 'Vietnam',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE2Ljk4LjIyNy40ODo1NTQvU3RyZWFtaW5nL0NoYW5uZWxzLzEwMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-116.99.196.219',
      lat: 16.1667,
      lng: 107.8333,
      name: 'Blackeye – Vietnam',
      city: 'Vietnam',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE2Ljk5LjE5Ni4yMTk6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-116.99.205.18',
      lat: 16.1667,
      lng: 107.8333,
      name: 'Blackeye – Vietnam',
      city: 'Vietnam',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE2Ljk5LjIwNS4xODo1NTQvU3RyZWFtaW5nL0NoYW5uZWxzLzEwMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-116.99.205.6',
      lat: 16.1667,
      lng: 107.8333,
      name: 'Blackeye – Vietnam',
      city: 'Vietnam',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE2Ljk5LjIwNS42OjU1NC9TdHJlYW1pbmcvQ2hhbm5lbHMvMTAx`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-116.99.207.123',
      lat: 16.1667,
      lng: 107.8333,
      name: 'Blackeye – Vietnam',
      city: 'Vietnam',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE2Ljk5LjIwNy4xMjM6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-117.102.227.134',
      lat: -6.175,
      lng: 106.8286,
      name: 'Blackeye – Indonesia',
      city: 'Indonesia',
      country: 'Indonesia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE3LjEwMi4yMjcuMTM0OjU1NC9saXZlL3ZpZGVvL3Byb2ZpbGUx`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-117.2.152.227',
      lat: 16.0685,
      lng: 108.2215,
      name: 'Blackeye – Da Nang',
      city: 'Da Nang',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE3LjIuMTUyLjIyNzo1NTQvU3RyZWFtaW5nL0NoYW5uZWxzLzEwMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-117.2.17.112',
      lat: 12.2552,
      lng: 109.1034,
      name: 'Blackeye – Diên Khánh',
      city: 'Diên Khánh',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE3LjIuMTcuMTEyOjU1NC9TdHJlYW1pbmcvQ2hhbm5lbHMvMTAx`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-117.2.186.95',
      lat: 16.4704,
      lng: 107.6009,
      name: 'Blackeye – Huế',
      city: 'Huế',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE3LjIuMTg2Ljk1OjU1NC9saXZlX21wZWc0LnNkcA==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-117.6.125.77',
      lat: 21.0184,
      lng: 105.8461,
      name: 'Blackeye – Hanoi',
      city: 'Hanoi',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE3LjYuMTI1Ljc3OjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-118.100.222.228',
      lat: 3.1572,
      lng: 101.6695,
      name: 'Blackeye – Kuala Lumpur',
      city: 'Kuala Lumpur',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE4LjEwMC4yMjIuMjI4OjU1NC9TdHJlYW1pbmcvQ2hhbm5lbHMvMTAx`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-118.100.236.103',
      lat: 3.1071,
      lng: 101.6139,
      name: 'Blackeye – Petaling Jaya',
      city: 'Petaling Jaya',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE4LjEwMC4yMzYuMTAzOjU1NC9jYW0vcmVhbG1vbml0b3I/Y2hhbm5lbD0xJnN1YnR5cGU9MA==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-118.200.74.200',
      lat: 1.3732,
      lng: 103.8431,
      name: 'Blackeye – Singapore',
      city: 'Singapore',
      country: 'Singapore',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE4LjIwMC43NC4yMDA6NTU0L2xpdmUvdmlkZW8vcHJvZmlsZTE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-118.69.104.105',
      lat: 10.822,
      lng: 106.6257,
      name: 'Blackeye – Ho Chi Minh City',
      city: 'Ho Chi Minh City',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE4LjY5LjEwNC4xMDU6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-118.70.78.145',
      lat: 21.0184,
      lng: 105.8461,
      name: 'Blackeye – Hanoi',
      city: 'Hanoi',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE4LjcwLjc4LjE0NTo1NTQvY2FtL3JlYWxtb25pdG9yP2NoYW5uZWw9MSZzdWJ0eXBlPTA=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-118.71.147.117',
      lat: 21.0184,
      lng: 105.8461,
      name: 'Blackeye – Hanoi',
      city: 'Hanoi',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE4LjcxLjE0Ny4xMTc6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-118.71.22.112',
      lat: 10.822,
      lng: 106.6257,
      name: 'Blackeye – Ho Chi Minh City',
      city: 'Ho Chi Minh City',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE4LjcxLjIyLjExMjo1NTQvbGl2ZS92aWRlby9wcm9maWxlMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-119.160.139.82',
      lat: 4.8852,
      lng: 114.9468,
      name: 'Blackeye – Bandar Seri Begawan',
      city: 'Bandar Seri Begawan',
      country: 'Brunei',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE5LjE2MC4xMzkuODI6NTU0L2NhbS9yZWFsbW9uaXRvcj9jaGFubmVsPTEmc3VidHlwZT0w`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-119.160.167.182',
      lat: 4.8852,
      lng: 114.9468,
      name: 'Blackeye – Bandar Seri Begawan',
      city: 'Bandar Seri Begawan',
      country: 'Brunei',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE5LjE2MC4xNjcuMTgyOjU1NC9jYW0vcmVhbG1vbml0b3I/Y2hhbm5lbD0xJnN1YnR5cGU9MA==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-119.18.16.130',
      lat: -37.8159,
      lng: 144.9669,
      name: 'Blackeye – Melbourne',
      city: 'Melbourne',
      country: 'Australia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE5LjE4LjE2LjEzMDo1NTQvMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-119.74.150.92',
      lat: 1.327,
      lng: 103.8972,
      name: 'Blackeye – Singapore',
      city: 'Singapore',
      country: 'Singapore',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE5Ljc0LjE1MC45Mjo1NTQvMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-119.86.180.157',
      lat: 29.5689,
      lng: 106.5577,
      name: 'Blackeye – Chongqing',
      city: 'Chongqing',
      country: 'China',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE5Ljg2LjE4MC4xNTc6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-119.92.29.68',
      lat: 14.5353,
      lng: 121.0061,
      name: 'Blackeye – Pasay',
      city: 'Pasay',
      country: 'Philippines',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTE5LjkyLjI5LjY4OjU1NC9TdHJlYW1pbmcvQ2hhbm5lbHMvMTAx`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-12.69.47.186',
      lat: 35.0427,
      lng: -120.476,
      name: 'Blackeye – Nipomo',
      city: 'Nipomo',
      country: 'United States',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTIuNjkuNDcuMTg2OjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-121.123.77.79',
      lat: 3.0384,
      lng: 101.7105,
      name: 'Blackeye – Seri Kembangan',
      city: 'Seri Kembangan',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTIxLjEyMy43Ny43OTo1NTQvY2FtL3JlYWxtb25pdG9yP2NoYW5uZWw9MSZzdWJ0eXBlPTA=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-121.202.192.16',
      lat: 22.2578,
      lng: 114.1657,
      name: 'Blackeye – Hong Kong',
      city: 'Hong Kong',
      country: 'Hong Kong',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTIxLjIwMi4xOTIuMTY6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-121.202.202.191',
      lat: 22.2578,
      lng: 114.1657,
      name: 'Blackeye – Hong Kong',
      city: 'Hong Kong',
      country: 'Hong Kong',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTIxLjIwMi4yMDIuMTkxOjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-121.6.87.199',
      lat: 1.3051,
      lng: 103.8447,
      name: 'Blackeye – Singapore',
      city: 'Singapore',
      country: 'Singapore',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTIxLjYuODcuMTk5OjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-121.7.80.171',
      lat: 1.4003,
      lng: 103.875,
      name: 'Blackeye – Singapore',
      city: 'Singapore',
      country: 'Singapore',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTIxLjcuODAuMTcxOjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-122.11.173.221',
      lat: 1.3596,
      lng: 103.8637,
      name: 'Blackeye – Singapore',
      city: 'Singapore',
      country: 'Singapore',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTIyLjExLjE3My4yMjE6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-175.100.21.248',
      lat: 11.5583,
      lng: 104.9121,
      name: 'Blackeye – Phnom Penh',
      city: 'Phnom Penh',
      country: 'Cambodia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTc1LjEwMC4yMS4yNDg6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-175.137.118.29',
      lat: 3.1408,
      lng: 101.6852,
      name: 'Blackeye – Kuala Lumpur',
      city: 'Kuala Lumpur',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTc1LjEzNy4xMTguMjk6NTU0L2NhbS9yZWFsbW9uaXRvcj9jaGFubmVsPTEmc3VidHlwZT0w`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-175.137.14.120',
      lat: 3.1408,
      lng: 101.6852,
      name: 'Blackeye – Kuala Lumpur',
      city: 'Kuala Lumpur',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTc1LjEzNy4xNC4xMjA6NTU0L2NhbS9yZWFsbW9uaXRvcj9jaGFubmVsPTEmc3VidHlwZT0w`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-175.138.105.38',
      lat: 3.1408,
      lng: 101.6852,
      name: 'Blackeye – Kuala Lumpur',
      city: 'Kuala Lumpur',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTc1LjEzOC4xMDUuMzg6NTU0L2NhbS9yZWFsbW9uaXRvcj9jaGFubmVsPTEmc3VidHlwZT0w`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-175.138.49.120',
      lat: 3.1408,
      lng: 101.6852,
      name: 'Blackeye – Kuala Lumpur',
      city: 'Kuala Lumpur',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTc1LjEzOC40OS4xMjA6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-175.139.224.9',
      lat: 3.1408,
      lng: 101.6852,
      name: 'Blackeye – Kuala Lumpur',
      city: 'Kuala Lumpur',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTc1LjEzOS4yMjQuOTo1NTQvY2FtL3JlYWxtb25pdG9yP2NoYW5uZWw9MSZzdWJ0eXBlPTA=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-175.143.192.125',
      lat: 3.0662,
      lng: 101.6189,
      name: 'Blackeye – Puchong Batu Dua Belas',
      city: 'Puchong Batu Dua Belas',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTc1LjE0My4xOTIuMTI1OjU1NC9TdHJlYW1pbmcvQ2hhbm5lbHMvMTAx`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-176.224.212.140',
      lat: 21.4913,
      lng: 39.1841,
      name: 'Blackeye – Jeddah',
      city: 'Jeddah',
      country: 'Saudi Arabia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTc2LjIyNC4yMTIuMTQwOjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-176.224.57.242',
      lat: 21.4913,
      lng: 39.1841,
      name: 'Blackeye – Jeddah',
      city: 'Jeddah',
      country: 'Saudi Arabia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTc2LjIyNC41Ny4yNDI6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-176.24.12.155',
      lat: 53.4096,
      lng: -2.9792,
      name: 'Blackeye – Liverpool',
      city: 'Liverpool',
      country: 'United Kingdom',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTc2LjI0LjEyLjE1NTo1NTQvMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-176.61.32.47',
      lat: 53.3627,
      lng: -6.2342,
      name: 'Blackeye – Dublin',
      city: 'Dublin',
      country: 'Ireland',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTc2LjYxLjMyLjQ3OjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-178.17.246.33',
      lat: 52.6049,
      lng: -1.1488,
      name: 'Blackeye – Leicester',
      city: 'Leicester',
      country: 'United Kingdom',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTc4LjE3LjI0Ni4zMzo1NTQvMA==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-178.214.73.210',
      lat: 31.9216,
      lng: 35.2033,
      name: 'Blackeye – Palestine',
      city: 'Palestine',
      country: 'Palestine',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTc4LjIxNC43My4yMTA6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-178.80.35.173',
      lat: 26.4336,
      lng: 50.1116,
      name: 'Blackeye – Dammam',
      city: 'Dammam',
      country: 'Saudi Arabia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTc4LjgwLjM1LjE3Mzo1NTQvMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-178.89.247.144',
      lat: 43.2525,
      lng: 76.9115,
      name: 'Blackeye – Almaty',
      city: 'Almaty',
      country: 'Kazakhstan',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTc4Ljg5LjI0Ny4xNDQ6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-180.247.81.42',
      lat: -7.254,
      lng: 112.7265,
      name: 'Blackeye – Surabaya',
      city: 'Surabaya',
      country: 'Indonesia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTgwLjI0Ny44MS40Mjo1NTQvbGl2ZS92aWRlby9wcm9maWxlMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-182.239.108.52',
      lat: 22.2578,
      lng: 114.1657,
      name: 'Blackeye – Hong Kong',
      city: 'Hong Kong',
      country: 'Hong Kong',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTgyLjIzOS4xMDguNTI6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-182.53.65.108',
      lat: 13.8582,
      lng: 100.478,
      name: 'Blackeye – Bangkok',
      city: 'Bangkok',
      country: 'Thailand',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTgyLjUzLjY1LjEwODo1NTQvMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-183.179.50.93',
      lat: 22.3163,
      lng: 114.1842,
      name: 'Blackeye – To Kwa Wan',
      city: 'To Kwa Wan',
      country: 'Hong Kong',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTgzLjE3OS41MC45Mzo1NTQvMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-184.163.89.197',
      lat: 45.4348,
      lng: -73.8629,
      name: 'Blackeye – Beaconsfield',
      city: 'Beaconsfield',
      country: 'Canada',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTg0LjE2My44OS4xOTc6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-184.60.75.201',
      lat: 34.8542,
      lng: -84.3279,
      name: 'Blackeye – Blue Ridge',
      city: 'Blue Ridge',
      country: 'United States',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTg0LjYwLjc1LjIwMTo1NTQvMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-184.64.42.255',
      lat: 51.126,
      lng: -114.1437,
      name: 'Blackeye – Calgary',
      city: 'Calgary',
      country: 'Canada',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTg0LjY0LjQyLjI1NTo1NTQvMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-184.71.187.50',
      lat: 49.2773,
      lng: -123.0679,
      name: 'Blackeye – Vancouver',
      city: 'Vancouver',
      country: 'Canada',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTg0LjcxLjE4Ny41MDo1NTQvU3RyZWFtaW5nL0NoYW5uZWxzLzEwMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-184.82.136.47',
      lat: 13.0508,
      lng: 100.9367,
      name: 'Blackeye – Bang Lamung',
      city: 'Bang Lamung',
      country: 'Thailand',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTg0LjgyLjEzNi40Nzo1NTQvMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-185.232.137.243',
      lat: 55.7386,
      lng: 37.6068,
      name: 'Blackeye – Russia',
      city: 'Russia',
      country: 'Russia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTg1LjIzMi4xMzcuMjQzOjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-185.30.117.247',
      lat: 43.5997,
      lng: 39.7293,
      name: 'Blackeye – Sochi',
      city: 'Sochi',
      country: 'Russia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMTg1LjMwLjExNy4yNDc6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-202.178.125.183',
      lat: 11.5634,
      lng: 104.9644,
      name: 'Blackeye – Phnom Penh',
      city: 'Phnom Penh',
      country: 'Cambodia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMjAyLjE3OC4xMjUuMTgzOjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-202.185.213.163',
      lat: 3.1612,
      lng: 101.5576,
      name: 'Blackeye – Shah Alam',
      city: 'Shah Alam',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMjAyLjE4NS4yMTMuMTYzOjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-202.185.228.143',
      lat: 3.1612,
      lng: 101.5576,
      name: 'Blackeye – Shah Alam',
      city: 'Shah Alam',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMjAyLjE4NS4yMjguMTQzOjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-202.187.32.180',
      lat: 3.1686,
      lng: 101.7035,
      name: 'Blackeye – Kuala Lumpur',
      city: 'Kuala Lumpur',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMjAyLjE4Ny4zMi4xODA6NTU0L2xpdmUvdmlkZW8vcHJvZmlsZTE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-202.188.54.226',
      lat: 3.107,
      lng: 101.6344,
      name: 'Blackeye – Petaling Jaya',
      city: 'Petaling Jaya',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMjAyLjE4OC41NC4yMjY6NTU0L2NhbS9yZWFsbW9uaXRvcj9jaGFubmVsPTEmc3VidHlwZT0w`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-202.57.28.98',
      lat: -6.175,
      lng: 106.8286,
      name: 'Blackeye – Indonesia',
      city: 'Indonesia',
      country: 'Indonesia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMjAyLjU3LjI4Ljk4OjU1NC9TdHJlYW1pbmcvQ2hhbm5lbHMvMTAx`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-203.24.247.132',
      lat: 39.0234,
      lng: -104.6926,
      name: 'Blackeye – Colorado Springs',
      city: 'Colorado Springs',
      country: 'United States',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMjAzLjI0LjI0Ny4xMzI6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-203.30.107.199',
      lat: 31.9216,
      lng: 35.2033,
      name: 'Blackeye – Palestine',
      city: 'Palestine',
      country: 'Palestine',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMjAzLjMwLjEwNy4xOTk6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-203.87.76.139',
      lat: -37.8024,
      lng: 144.9659,
      name: 'Blackeye – Melbourne',
      city: 'Melbourne',
      country: 'Australia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMjAzLjg3Ljc2LjEzOTo1NTQvMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-210.213.85.35',
      lat: 14.5185,
      lng: 121.0689,
      name: 'Blackeye – Taguig',
      city: 'Taguig',
      country: 'Philippines',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMjEwLjIxMy44NS4zNTo1NTQvU3RyZWFtaW5nL0NoYW5uZWxzLzEwMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-217.165.123.233',
      lat: 25.0734,
      lng: 55.2979,
      name: 'Blackeye – Dubai',
      city: 'Dubai',
      country: 'United Arab Emirates',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMjE3LjE2NS4xMjMuMjMzOjU1NC9TdHJlYW1pbmcvQ2hhbm5lbHMvMTAx`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-217.165.145.197',
      lat: 24.4542,
      lng: 54.406,
      name: 'Blackeye – Abu Dhabi',
      city: 'Abu Dhabi',
      country: 'United Arab Emirates',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMjE3LjE2NS4xNDUuMTk3OjU1NC9TdHJlYW1pbmcvQ2hhbm5lbHMvMTAx`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-218.111.20.80',
      lat: 1.4834,
      lng: 103.6339,
      name: 'Blackeye – Iskandar Puteri',
      city: 'Iskandar Puteri',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMjE4LjExMS4yMC44MDo1NTQvY2FtL3JlYWxtb25pdG9yP2NoYW5uZWw9MSZzdWJ0eXBlPTA=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-218.250.61.18',
      lat: 22.2578,
      lng: 114.1657,
      name: 'Blackeye – Hong Kong',
      city: 'Hong Kong',
      country: 'Hong Kong',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMjE4LjI1MC42MS4xODo1NTQvMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-2.51.169.166',
      lat: 25.0734,
      lng: 55.2979,
      name: 'Blackeye – Dubai',
      city: 'Dubai',
      country: 'United Arab Emirates',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMi41MS4xNjkuMTY2OjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-2.97.222.69',
      lat: 52.5279,
      lng: -2.0705,
      name: 'Blackeye – Tipton',
      city: 'Tipton',
      country: 'United Kingdom',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMi45Ny4yMjIuNjk6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-222.253.64.99',
      lat: 10.8126,
      lng: 106.678,
      name: 'Blackeye – Go Vap',
      city: 'Go Vap',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMjIyLjI1My42NC45OTo1NTQvbGl2ZS92aWRlby9wcm9maWxlMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-222.254.54.183',
      lat: 21.0333,
      lng: 105.9,
      name: 'Blackeye – Long Bien',
      city: 'Long Bien',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMjIyLjI1NC41NC4xODM6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-223.18.59.50',
      lat: 22.4362,
      lng: 114.0345,
      name: 'Blackeye – Yuen Long San Hui',
      city: 'Yuen Long San Hui',
      country: 'Hong Kong',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMjIzLjE4LjU5LjUwOjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-223.19.244.179',
      lat: 22.3356,
      lng: 114.1847,
      name: 'Blackeye – Kowloon City',
      city: 'Kowloon City',
      country: 'Hong Kong',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMjIzLjE5LjI0NC4xNzk6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-223.205.186.92',
      lat: 14.4466,
      lng: 100.6188,
      name: 'Blackeye – Phra Nakhon Si Ayutthaya',
      city: 'Phra Nakhon Si Ayutthaya',
      country: 'Thailand',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMjIzLjIwNS4xODYuOTI6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-223.205.69.211',
      lat: 13.5341,
      lng: 100.286,
      name: 'Blackeye – Samut Sakhon',
      city: 'Samut Sakhon',
      country: 'Thailand',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMjIzLjIwNS42OS4yMTE6NTU0L2NhbS9yZWFsbW9uaXRvcj9jaGFubmVsPTEmc3VidHlwZT0w`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-27.2.34.213',
      lat: 10.822,
      lng: 106.6257,
      name: 'Blackeye – Ho Chi Minh City',
      city: 'Ho Chi Minh City',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMjcuMi4zNC4yMTM6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-27.32.37.6',
      lat: -32.1773,
      lng: 115.9873,
      name: 'Blackeye – Perth',
      city: 'Perth',
      country: 'Australia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMjcuMzIuMzcuNjo1NTQvU3RyZWFtaW5nL0NoYW5uZWxzLzEwMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-27.64.1.190',
      lat: 10.822,
      lng: 106.6257,
      name: 'Blackeye – Ho Chi Minh City',
      city: 'Ho Chi Minh City',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAMjcuNjQuMS4xOTA6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-42.117.120.210',
      lat: 10.822,
      lng: 106.6257,
      name: 'Blackeye – Ho Chi Minh City',
      city: 'Ho Chi Minh City',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVANDIuMTE3LjEyMC4yMTA6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-42.119.241.87',
      lat: 21.0184,
      lng: 105.8461,
      name: 'Blackeye – Hanoi',
      city: 'Hanoi',
      country: 'Vietnam',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVANDIuMTE5LjI0MS44Nzo1NTQvU3RyZWFtaW5nL0NoYW5uZWxzLzEwMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-42.200.124.181',
      lat: 22.2578,
      lng: 114.1657,
      name: 'Blackeye – Hong Kong',
      city: 'Hong Kong',
      country: 'Hong Kong',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVANDIuMjAwLjEyNC4xODE6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-42.60.254.21',
      lat: 1.3352,
      lng: 103.8529,
      name: 'Blackeye – Singapore',
      city: 'Singapore',
      country: 'Singapore',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVANDIuNjAuMjU0LjIxOjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-45.3.59.83',
      lat: 41.8905,
      lng: 12.5127,
      name: 'Blackeye – Rome',
      city: 'Rome',
      country: 'Italy',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVANDUuMy41OS44Mzo1NTQvMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-58.136.113.103',
      lat: 18.7857,
      lng: 98.9736,
      name: 'Blackeye – Chiang Mai',
      city: 'Chiang Mai',
      country: 'Thailand',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVANTguMTM2LjExMy4xMDM6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-58.136.195.94',
      lat: 13.733,
      lng: 100.4865,
      name: 'Blackeye – Bangkok',
      city: 'Bangkok',
      country: 'Thailand',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVANTguMTM2LjE5NS45NDo1NTQvMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-58.182.69.139',
      lat: 1.3153,
      lng: 103.9143,
      name: 'Blackeye – Singapore',
      city: 'Singapore',
      country: 'Singapore',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVANTguMTgyLjY5LjEzOTo1NTQvbGl2ZS92aWRlby9wcm9maWxlMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-58.185.24.201',
      lat: 1.2872,
      lng: 103.8507,
      name: 'Blackeye – Singapore',
      city: 'Singapore',
      country: 'Singapore',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVANTguMTg1LjI0LjIwMTo1NTQvbGl2ZS92aWRlby9wcm9maWxlMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-58.6.114.189',
      lat: -27.4994,
      lng: 152.9042,
      name: 'Blackeye – Brisbane',
      city: 'Brisbane',
      country: 'Australia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVANTguNi4xMTQuMTg5OjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-59.149.5.173',
      lat: 22.2578,
      lng: 114.1657,
      name: 'Blackeye – Hong Kong',
      city: 'Hong Kong',
      country: 'Hong Kong',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVANTkuMTQ5LjUuMTczOjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-60.50.173.236',
      lat: 2.9283,
      lng: 101.6511,
      name: 'Blackeye – Cyberjaya',
      city: 'Cyberjaya',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVANjAuNTAuMTczLjIzNjo1NTQvU3RyZWFtaW5nL0NoYW5uZWxzLzEwMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-60.50.252.251',
      lat: 2.9283,
      lng: 101.6511,
      name: 'Blackeye – Cyberjaya',
      city: 'Cyberjaya',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVANjAuNTAuMjUyLjI1MTo1NTQvbGl2ZS92aWRlby9wcm9maWxlMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-60.50.36.85',
      lat: 2.9283,
      lng: 101.6511,
      name: 'Blackeye – Cyberjaya',
      city: 'Cyberjaya',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVANjAuNTAuMzYuODU6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-60.53.240.93',
      lat: 3.0617,
      lng: 101.4621,
      name: 'Blackeye – Klang',
      city: 'Klang',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVANjAuNTMuMjQwLjkzOjU1NC9saXZlL3ZpZGVvL3Byb2ZpbGUx`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-60.54.31.228',
      lat: 2.9283,
      lng: 101.6511,
      name: 'Blackeye – Cyberjaya',
      city: 'Cyberjaya',
      country: 'Malaysia',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVANjAuNTQuMzEuMjI4OjU1NC9jYW0vcmVhbG1vbml0b3I/Y2hhbm5lbD0xJnN1YnR5cGU9MA==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-61.13.192.130',
      lat: 1.3732,
      lng: 103.8431,
      name: 'Blackeye – Singapore',
      city: 'Singapore',
      country: 'Singapore',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVANjEuMTMuMTkyLjEzMDo1NTQvMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-61.244.131.181',
      lat: 22.2848,
      lng: 114.1703,
      name: 'Blackeye – Wan Chai',
      city: 'Wan Chai',
      country: 'Hong Kong',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVANjEuMjQ0LjEzMS4xODE6NTU0LzE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-61.244.145.122',
      lat: 22.2578,
      lng: 114.1657,
      name: 'Blackeye – Hong Kong',
      city: 'Hong Kong',
      country: 'Hong Kong',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVANjEuMjQ0LjE0NS4xMjI6NTU0L1N0cmVhbWluZy9DaGFubmVscy8xMDE=`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-78.101.24.89',
      lat: 25.2925,
      lng: 51.5321,
      name: 'Blackeye – Doha',
      city: 'Doha',
      country: 'Qatar',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVANzguMTAxLjI0Ljg5OjU1NC8x`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-82.64.239.105',
      lat: 48.8558,
      lng: 2.3494,
      name: 'Blackeye – France',
      city: 'France',
      country: 'France',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAODIuNjQuMjM5LjEwNTo1NTQvU3RyZWFtaW5nL0NoYW5uZWxzLzEwMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-83.70.32.5',
      lat: 52.9598,
      lng: -7.2114,
      name: 'Blackeye – Timahoe',
      city: 'Timahoe',
      country: 'Ireland',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAODMuNzAuMzIuNTo1NTQvU3RyZWFtaW5nL0NoYW5uZWxzLzEwMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-84.229.55.71',
      lat: 31.9642,
      lng: 34.7876,
      name: 'Blackeye – Rishon LeTsiyyon',
      city: 'Rishon LeTsiyyon',
      country: 'Israel',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAODQuMjI5LjU1LjcxOjU1NC9TdHJlYW1pbmcvQ2hhbm5lbHMvMTAx`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-85.130.149.55',
      lat: 32.0804,
      lng: 34.7807,
      name: 'Blackeye – Tel Aviv',
      city: 'Tel Aviv',
      country: 'Israel',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAODUuMTMwLjE0OS41NTo1NTQvU3RyZWFtaW5nL0NoYW5uZWxzLzEwMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-85.130.203.49',
      lat: 32.0804,
      lng: 34.7807,
      name: 'Blackeye – Tel Aviv',
      city: 'Tel Aviv',
      country: 'Israel',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAODUuMTMwLjIwMy40OTo1NTQvU3RyZWFtaW5nL0NoYW5uZWxzLzEwMQ==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
    {
      id: 'blackeye-92.96.95.203',
      lat: 24.4542,
      lng: 54.406,
      name: 'Blackeye – Abu Dhabi',
      city: 'Abu Dhabi',
      country: 'United Arab Emirates',
      feed_url: `${STREAM_HOST}/api/stream?rtsp=cnRzcDovL2JsYWNrZXllOkJsYWNrR2xvYmVAOTIuOTYuOTUuMjAzOjU1NC9jYW0vcmVhbG1vbml0b3I/Y2hhbm5lbD0xJnN1YnR5cGU9MA==`,
      stream_type: 'jpg',
      source: 'Blackeye',
    },
  ];
}
